exports.favorite = require('./db-favorite')
exports.rating = require('./db-rating')
exports.route = require('./db-route')
exports.session = require('./db-session')
exports.user = require('./db-user')
exports.waypoint = require('./db-waypoint')